services:
  AxarDB:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/Logging
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
